CREATE TABLE IF NOT EXISTS department (
  department_id int NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  department_name text NOT NULL
);

CREATE TABLE IF NOT EXISTS employee (
  employee_id int NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name text NOT NULL,
  department_id int NOT NULL REFERENCES department (department_id)
);